#!/bin/bash
#

# This script is as described in drivers/char/random.c in the
# kernel sources.  It's to preserve the entropy pool over a
# reboot to ensure that /dev/random isn't predictable on
# power up.

PROG="random"
RANDOM_SEED=/var/ipaccess/random-seed
RETVAL=0

start() {
    echo "Initializing random number generator..."
    # Carry a random seed from start-up to start-up
    # Load and then save the whole entropy pool
    if [ -f $RANDOM_SEED ]; then
        cat $RANDOM_SEED >/dev/urandom
    else
        touch $RANDOM_SEED
    fi
    chmod 600 $RANDOM_SEED
    # Following line ensures that the seed will be different
    # on the next run, even if the AP crashes without running
    # the shutdown script.
    dd if=/dev/urandom of=$RANDOM_SEED count=1 bs=512
    echo "OK"
}

stop() {
    # Carry a random seed from shut-down to start-up
    # Save the whole entropy pool
    echo "Saving random seed..."
    touch $RANDOM_SEED
    chmod 600 $RANDOM_SEED
    dd if=/dev/urandom of=$RANDOM_SEED count=1 bs=512
    echo "OK"
}

restart() {
    stop
    start
    RETVAL=$?
}

# processing of command line
case "$1" in
    start)
        start
    	;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
