#!/bin/sh
#
# syslog        Startup the system log
#
#

. /etc/init.d/functions

SYSLOG="/sbin/syslogd"
KLOG="/sbin/klogd"
BOOT_LOG=/var/log/boot.log
RETVAL=0

if [ "`echo $FS_VARIANT | grep -c 205`" = "1" ]; then
    # reduced log size for 64Mb system
    ARGS_SYSLOG="-s 100"
else
    ARGS_SYSLOG="-s 200"
fi


start() {
    if [ ! -f $BOOT_LOG ]; then
        dmesg -c > $BOOT_LOG
    else
        echo "$BOOT_LOG already exists"
    fi
    
    startapp `basename $SYSLOG` $SYSLOG
    startapp `basename $KLOG`   $KLOG
}

startapp()
{
    echo -n "Starting $1: "
    is_app_running $1
    if [ $? != $TRUE ]; then
        if [ $1 = "syslogd" ]; then
            $2 $ARGS_SYSLOG
        else
            $2
        fi
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo OK
        else
            echo FAILURE
        fi
    else
        echo "FAILURE (already running)"
    fi
}

stop()
{
    stopapp `basename $KLOG`
    stopapp `basename $SYSLOG`
}

stopapp() {
    echo -n "Stopping $1: "
    kill -9 `pidof -o $$ -o $PPID -o %PPID $1` >/dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo OK
    else
        echo FAILURE
    fi
}

restart() {
    stop
    start
    RETVAL=$?
}

# processing of command line
case "$1" in
    start)
        start
    	;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
