#!/bin/bash
#
# Sets the reboot cause as internal application. Exit status
# of 0 indicates success, anything else is a failure.
#
REBOOT_CAUSE=/tmp/.reboot_cause

usage()
{
    echo "USAGE: $0 <causeCode|causeText> [rebootCauseText]"
    exit 99
}

if [ $# != 1 -a $# != 2 ]; then
    usage
fi

echo "CAUSE=$1" > $REBOOT_CAUSE
RET=$?

if [ $? = 0 -a $# = 2 ]; then
    echo "REBOOT_CAUSE_TEXT=\"$2\"" >> $REBOOT_CAUSE
    RET=$?
fi

exit $RET
